### ISSUE TITLE
jq missing error

### ISSUE THREAD

**Issue by kassemz** [lpadula/lemp-utils-scripts#2]
```
/root/brolit-shell/libs/local/json_helper.sh: line 29: jq: command not found
/root/brolit-shell/libs/local/json_helper.sh: line 29: jq: command not found
/root/brolit-shell/libs/local/json_helper.sh: line 29: jq: command not found

```

Getting these errors and after ` apt install jq`, getting:
`jq: error (at <stdin>:152): Cannot iterate over null (null)`

On Ubuntu 20.04.3

**Comment by lpadula** [comment]
Hi kassemz! It's strange, the script check for the jq package and it will try to install it.

About:
jq: error (at <stdin>:152): Cannot iterate over null (null)

In the new release I have made a huge refactor on BROLIT config. Now you need to configure the **brolit_conf.json** (should be on root directory). I recommend you delete it and run the script, it will prompt you to create a new configuration file. Then exit, configure the file, and run the **runner.sh** again.

 In the next days I will update the documentation.

**Comment by lpadula** [comment]
Hi, its working now, please remove the config file, update brolit-shell and execute de runner again.
