### ISSUE TITLE
Disable WP_DEBUG WP_SCRIPTS in PRODUCTION

### ISSUE THREAD

**Issue by Franquetex** [lpadula/lemp-utils-scripts#4]
When migrating from dev/stage to production, in the `wp-config.php` these constants should be disabled (false). To prevent logging notices and errors (WP_DEBUG) and to load minified files from the gutenberg editor (WP_SCRIPTS)

**Comment by lpadula** [comment]
Hi, please update your brolit-shell version with a git pull 🎉 

Commit: [f0ed047](https://github.com/lpadula/brolit-shell/commit/f0ed047adc43b486301775ac32b27f0743db0c16)
