### ISSUE TITLE
Isolate sites

### ISSUE THREAD

**Issue by kassemz** [lpadula/lemp-utils-scripts#6]
Hi

Thanks for working on this.

I like the fact that this is a lightweight option however there is a security issue currently which is sites are running with one user (www-data).

I suggest that each site = Linux user and its own PHP pool configuration so sites are isolated from each other.

Others describe the same thing on another similar project here:
https://github.com/WordOps/WordOps/issues/425
https://github.com/WordOps/WordOps/issues/41

**Comment by lpadula** [comment]
Hi! 

Nice suggestion, I will add this to the roadmap.
